### ISSUE TITLE
Select Database Platform 

### ISSUE THREAD

**Issue by norrisaftcc** [cookm3246/CSC-289-Capstone-Project#2]
Q: What is the **best DB** to choose to use with C# for this project?

Concerns:
[ ] must work well with C#
[ ] support ORM / Entity Framework? (optional?)
[ ] network connection issues? (school firewall)

Comments from Buckwell:
* single database
* locally served

**Comment by norrisaftcc** [comment]
Solicit feedback from @cookm3246 @Dashisaru @warburgj9467 and @norrisaftcc

**Comment by norrisaftcc** [comment]
possible candidates:
* sql server
* sql server express
* oracle 12c
* mysql

**Comment by Dashisaru** [comment]
I think to keep it simple for now until we bring in an outside entity, using the built in database in visual studios would be easiest. For future reference though, I'm thinking that mysql seems to be a better solid option for our end game. Subject to change though.

**Comment by warburgj9467** [comment]
I vote MySQL just because it is what I am most familiar with and has an
easy to use GUI.  Thank you Mr. Norris!

**Comment by warburgj9467** [comment]
@Dashisaru   Tony, this is a helpful article about databases that work with visual studio.  Please read and make a recommendation based on the one you want to work with.  Thank you!   (MySQL is listed)  https://docs.microsoft.com/en-us/visualstudio/data-tools/installing-database-systems-tools-and-samples

**Comment by warburgj9467** [comment]
I have closed because I think we know what we are using, Azure in Visual Studio to start and then MySQL.
