### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by Dashisaru** [cookm3246/CSC-289-Capstone-Project#3]
Not really important at this point, but I do believe we need to come up with a name for this program. A name I feel more or less would help in the scheme of things. Again, not really important but something to think about for when we do the alpha and pitch presentation.

**Comment by warburgj9467** [comment]
Possibilities:  Child Tracker System
                     DSS System
                     DSS Case Tracker
                      Case Share System
@Dashisaru 
@cookm3246 
@ANorris

**Comment by warburgj9467** [comment]
Maybe just Case Tracker?

**Comment by cookm3246** [comment]
Maybe try to stay away from using DSS in the name since we aren't actually affiliated with them. We could stick with calling it case tracker for the time being just so we have something to call it other than our capstone project.

**Comment by Dashisaru** [comment]
I agree with staying away from DSS. I think Case Tracker would be a good name for the time being. Name can always be changed but I think it would be a good temp name.

**Comment by warburgj9467** [comment]
I am closing this issue because I think we are settled on 'Case Tracker'.
